### ISSUE TITLE
dashStyle is not exported

### ISSUE THREAD

**Issue by gasnier** [A----/highcharts-export-clientside#19]
Series with a dash style are exported without the style (it works when we use the export server)
http://jsfiddle.net/pscjzhe4/197/

**Comment by A----** [comment]
OK well, it seems that that's due to an old version/tweak/something on the `canvas-tools` module from the `canvg` library.

`canvg` seems to handle the `stroke-dasharray` attribute OK: https://github.com/gabelerner/canvg/blob/master/canvg.js#L960
But I can't find a reference to that one in the fork from Highcharts: https://a----.github.io/highcharts-export-clientside/bower_components/highcharts/modules/canvas-tools.src.js

Now that's something that appears to change *a lot* in the recent versions. `master` doesn't have a `canvas-tools` extension anymore, but a new renderer (https://github.com/highslide-software/highcharts.com/tree/master/js/modules).
Also, they have their own “offline export“ plugin. But I don't think that it'll help you in that case (you still have to include `canvg` and they package the 1.1 version).

So I tried to include the latest `canvg` version and surprise: it works!
I had issues with old revisions of that library, like title appearing two times.
Here's the updated version: http://jsfiddle.net/pscjzhe4/198/

Please include both `rgbcolor` and `canvg` for this to work.

**Comment by gasnier** [comment]
Perfect, thank you !
