### ISSUE TITLE
IE - Which shim is required to get this working?

### ISSUE THREAD

**Issue by tallsam** [A----/highcharts-export-clientside#4]

**Comment by A----** [comment]
IE10+ are supported, see http://a----.github.io/highcharts-export-clientside/#compatibility .

With IE9 and below, it gets tricky. First, `canvas` has been implemented in IE9, so you will want a polyfill for that. [excanvas](https://code.google.com/p/explorercanvas/) won't do the job since it uses a VML fallback which there's no way to rasterize according to [this](https://code.google.com/p/explorercanvas/issues/detail?id=77). So Flash fallback it is. [fxcanvas](https://code.google.com/p/fxcanvas/) has a `toDataUrl()` method.

Next is the download part, which is the real issue. For text exports, there's this [ugly as fuck](https://github.com/koffsyrup/FileSaver.js/blob/master/FileSaver.js#L263) trick. For images though, it would require a Flash object. I couldn't find anything small and easy to use though (list existing of polyfill [here](https://github.com/Modernizr/Modernizr/wiki/HTML5-Cross-Browser-Polyfills#file-api)).

I'm sorry but I don't have the time to work on a IE9- solution. Plus, chances are high that nothing will go as planned on those platforms. To export an PNG, you'd have to:
* Use HighCharts export plugin to render a SVG version of it;
* Use canvg to go from the SVG to a rasterized image ;
* canvg would have to use a Flash polyfill since `canvas` doesn't exist on IE8 ;
* Use another Flash polyfill to download the file.

What could go wrong? :smile:
