### ISSUE TITLE
Exported file should use the chart title for filename, as done in Highcharts export-csv module

### ISSUE THREAD

**Issue by tomascassidy** [A----/highcharts-export-clientside#5]
https://github.com/highslide-software/export-csv/blob/master/export-csv.js#L185
https://github.com/highslide-software/export-csv/blob/master/export-csv.js#L194

The exported file should do what the export-csv plugin does and use the chart title as the downloaded filename, defaulting back to the existing 'chart' string if no title exists.

**Comment by A----** [comment]
Sorry but that won't happen or at least that way. The documentation for the HighCharts export plugin (PNG/…) states that default filename is “chart” without the extension:
http://api.highcharts.com/highcharts#exporting.filename

`export-csv` in the other, while done by the same guys is clearly unofficial and patched in under a unified API.

What I can do though is extend the actual API by allowing functions to be used for this configuration option, and expose one so that's either to achieve. You could actually define it globally.

**Comment by tomascassidy** [comment]
Extending the API would be nice in the long term.  I didn't realise the official API defined "chart" as the default.

**Comment by A----** [comment]
I did what I said. Documentation has also been updated.
Check out the website which does use the constant.
